# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp
solution: Dynamitey.sln
env:
  global:
    - EnableNuGetPackageRestore=true
    
mono: beta
dotnet: 1.0.4
dist: trusty

install:
  - msbuild /ver

script:
  - ./build.fsx

branches:
  only:
    - master
