# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
  allow_failures:
    - os: linux

solution: Dynamitey.sln

env:
  global:
    - EnableNuGetPackageRestore=true
    
mono: beta
dotnet: 1.0.4

install:
  - msbuild /ver

script:
  - ./build.fsx

branches:
  only:
    - master

after_failure:
  - ls ./packages